Instagram and FB Parser
nickrgarner/google-takeout-data-mining pull request #7
Opened 2021-11-02 17:25 UTC by VamsiMadhur

2021-11-05 20:47 UTC, yrahul3910 requested changes
Please flesh out your comments, and rename.

2021-11-05 20:47 UTC, yrahul3910 commented on userdata_mining/mining/facebook.py
> +def parse_fb_advitisors(user, data_path='.'):
please rename

2021-11-05 20:47 UTC, yrahul3910 commented on userdata_mining/mining/facebook.py
> +    Mines
??

2021-11-05 20:47 UTC, yrahul3910 commented on userdata_mining/mining/facebook.py
> +    Mines
??

2021-11-05 20:47 UTC, yrahul3910 commented on userdata_mining/mining/instagram.py
> +    Mines
?

2021-11-08 22:53 UTC, yrahul3910 requested changes
Nice work! In the FbInstaDataMiner class, please return the embeddings as done in the GoogleDataMiner class.

2021-11-10 16:11 UTC, nickrgarner requested changes
Need to import facebook.py and instagram.py into `userdata_mining/mining/__init__.py`. See https://github.com/nickrgarner/google-takeout-data-mining/pull/9/files

2021-11-10 16:11 UTC, nickrgarner commented on userdata_mining/mining/miner.py
> +
Missing blocks for loading cached embeddings if data is None

2021-11-10 16:11 UTC, nickrgarner commented on userdata_mining/mining/miner.py
> +
Missing printout of data details

2021-11-12 22:41 UTC, yrahul3910 requested changes
In userdata_mining/mining/__init__.py, please add a newline at the end of the file, and I will approve.

2021-11-13 02:24 UTC, nickrgarner approved these changes
Good work! Thanks for addressing all the changes

2021-11-13 02:24 UTC, nickrgarner approved these changes

2021-11-13 02:25 UTC, nickrgarner approved these changes

2021-11-13 02:56 UTC, yrahul3910 approved these changes

2021-11-13 02:56 UTC, merged